// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwucUqh6Dv8m1fv6_1eTM-M-1_PlLi0PQ',
    appId: '1:739656987111:web:c0ffd7036b1184aabd8d42',
    messagingSenderId: '739656987111',
    projectId: 'redux-http-abc1a',
    authDomain: 'redux-http-abc1a.firebaseapp.com',
    databaseURL: 'https://redux-http-abc1a-default-rtdb.firebaseio.com',
    storageBucket: 'redux-http-abc1a.appspot.com',
    measurementId: 'G-GZFBCKGZBJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMdSrUa1Uwo9s-6qaKaJwMbDVBxO7c1ms',
    appId: '1:739656987111:android:ce521e43eb8246b3bd8d42',
    messagingSenderId: '739656987111',
    projectId: 'redux-http-abc1a',
    databaseURL: 'https://redux-http-abc1a-default-rtdb.firebaseio.com',
    storageBucket: 'redux-http-abc1a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe5QRyKyLnfkZrAx2y-R1bqsZlOEed01Y',
    appId: '1:739656987111:ios:c3d5584d928023afbd8d42',
    messagingSenderId: '739656987111',
    projectId: 'redux-http-abc1a',
    databaseURL: 'https://redux-http-abc1a-default-rtdb.firebaseio.com',
    storageBucket: 'redux-http-abc1a.appspot.com',
    iosClientId: '739656987111-s599f8if221obl2nlvc2sc5lp1jbi3ua.apps.googleusercontent.com',
    iosBundleId: 'ng.think-alpha.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAe5QRyKyLnfkZrAx2y-R1bqsZlOEed01Y',
    appId: '1:739656987111:ios:c3d5584d928023afbd8d42',
    messagingSenderId: '739656987111',
    projectId: 'redux-http-abc1a',
    databaseURL: 'https://redux-http-abc1a-default-rtdb.firebaseio.com',
    storageBucket: 'redux-http-abc1a.appspot.com',
    iosClientId: '739656987111-s599f8if221obl2nlvc2sc5lp1jbi3ua.apps.googleusercontent.com',
    iosBundleId: 'ng.think-alpha.mynotes',
  );
}
